# Hologram will run from same directory where this config file resides
# All paths should be relative to there

# The directory containing the source files to parse recursively
source: ./styles

# The directory that hologram will build to
destination: ./docs

# The assets needed to build the docs (includes header.html,
# footer.html, etc)
# You may put doc related assets here too: images, css, etc.
documentation_assets: ./doc_assets

# The folder that contains templates for rendering code examples.
# If you want to change the way code examples appear in the styleguide,
# modify the files in this folder
code_example_templates: ./code_example_templates

# The folder that contains custom code example renderers.
# If you want to create additional renderers that are not provided
# by Hologram (i.e. coffeescript renderer, jade renderer, etc)
# place them in this folder
code_example_renderers: ./code_example_renderers


css_include:
  - '../../Resources/Public/css/style.css'

js_include:
  - '../bower_components/jQuery/dist/jquery.min.js'
  - '../bower_components/slick-carousel/slick/slick.js'
  - '../bower_components/jqueryui/jquery-ui.js'
  - '../bower_components/accounting.js/accounting.js'
  - '../bower_components/moment/moment.js'
  - '../bower_components/swd-calculator/src/jquery-swd-calculator.js'
  - '../scripts/calculator.js'
  - '../scripts/checkbox-link.js'
  - '../scripts/expandable-box.js'
  - '../scripts/service-nav.js'
  - '../scripts/slider.js'
  - '../scripts/site-footer-nav.js'
  - '../scripts/tab-teaser.js'
  - '../scripts/search.js'
  - '../scripts/no-transitions.js'
  - '../scripts/main-nav.js'
  - '../scripts/news.js'
  - '../scripts/form.js'
  - '../scripts/table.js'

# Mark which category should be the index page
# Alternatively, you may have an index.md in the documentation assets
# folder instead of specifying this config.
index: basics

# To additionally output navigation for top level sections, set the value to
# 'section'. To output navigation for sub-sections,
# set the value to `all`
nav_level: all

# Hologram displays warnings when there are issues with your docs
# (e.g. if a component's parent is not found, if the _header.html and/or
#  _footer.html files aren't found)
# If you want Hologram to exit on these warnings, set the value to 'true'
# (Default value is 'false')
exit_on_warnings: false